### ISSUE TITLE
Can't install it using pip

### ISSUE THREAD

**Issue by elieobeid7** [mamins1376/Subscene-API#5]
I'm trying to install it using pip in virtualenv
```

pip install https://github.com/mamins1376/Subscene-API/archive/master.zip
Collecting https://github.com/mamins1376/Subscene-API/archive/master.zip
  Downloading https://github.com/mamins1376/Subscene-API/archive/master.zip
     \ 20kB 102kB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/subscene_api.egg-info
    writing pip-egg-info/subscene_api.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/subscene_api.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/subscene_api.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/subscene_api.egg-info/SOURCES.txt'
    error: package directory 'subscene' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_bGT3t-build/

```
If I install it using

`pip install subscene-api`

It gets installed correctly but I can't import it, 

`import subscene # gives no module found`

**Comment by gowthamgts** [comment]
It is reproducible. Looks like BeautifulSoup requirement is not getting installed when `pip install subscene-api` is issued.

**Comment by elieobeid7** [comment]
Even if I install beautifulsoup before installing subscene, it won't work.

**Comment by mamins1376** [comment]
Currently I'm trying to merge this project with [subliminal](https://github.com/mamins1376/subliminal) as a provider; so this repository will be deleted and no more supported. see [related pull request](https://github.com/Diaoul/subliminal/pull/740) for development status.

Thank you for your bug report.
